package pl.startrader.model.character;

import pl.startrader.Dice;

public class CharacterFactory {

    public static Character getCharacter(String role, Integer criminalConnections, Integer politicalConnections,
                                         Integer economicConnections) {

        if ("Crew".equalsIgnoreCase(role)) {
            return new Character(Role.CREW, criminalConnections, politicalConnections, economicConnections);
        } else if ("Administrator".equalsIgnoreCase(role)) {
            return new Character(Role.ADMINISTRATOR, criminalConnections,politicalConnections,economicConnections);
        } else if ("Spy".equalsIgnoreCase(role)) {
            return new Character(Role.SPY, criminalConnections, politicalConnections, economicConnections);
        } else {
            return null;
        }
    }


    /**
     *
     * @param role  String representation of Role enum - "Crew" / "Administrator" / "Spy" /
     * @param skill String representation of proficiency - "Weak" / "Mediocre" / "Superior" / "Random"
     * @return  Character generated by given attributes.
     */
    public static Character generateCharacter(String skill, String role) {

        Integer criminal;
        Integer political;
        Integer economic;

        if ("Weak".equalsIgnoreCase(skill)) {
            criminal = Dice.getInstance().throwDoubleBorderedDice(1,4);
            political = Dice.getInstance().throwDoubleBorderedDice(1,4);
            economic = Dice.getInstance().throwDoubleBorderedDice(1,4);

            getCharacter(role, criminal, political, economic);

        } else if ("Mediocre".equalsIgnoreCase(skill)) {
            criminal = Dice.getInstance().throwDoubleBorderedDice(4,7);
            political = Dice.getInstance().throwDoubleBorderedDice(4,7);
            economic = Dice.getInstance().throwDoubleBorderedDice(4,7);

            getCharacter(role, criminal, political, economic);

        } else if ("Superior".equalsIgnoreCase(skill)) {
            criminal = Dice.getInstance().throwDoubleBorderedDice(7,10);
            political = Dice.getInstance().throwDoubleBorderedDice(7,10);
            economic = Dice.getInstance().throwDoubleBorderedDice(7,10);

            getCharacter(role, criminal, political, economic);

        } else if ("Random".equalsIgnoreCase(skill)) {
            criminal = Dice.getInstance().throwDoubleBorderedDice(0,10);
            political = Dice.getInstance().throwDoubleBorderedDice(0,10);
            economic = Dice.getInstance().throwDoubleBorderedDice(0,10);

            getCharacter(role, criminal, political, economic);

        }

        return null;
    }
}
